/**
 * @file GENERATED — do not edit.
 *
 * Derived from asciidoctor-pdf 2.3.24's own `base-theme.yml` and `default-theme.yml` by
 * `packages/shared/scripts/generate-theme-descriptors.mjs`. Regenerate after a gem bump:
 *
 *     `pnpm --filter @asciidocollab/shared generate:theme-descriptors`
 *
 * Prose descriptions are NOT here — they live in the hand-maintained `theme-descriptions.ts` and
 * are merged in `theme-catalogue.ts`.
 *
 */

import type { GeneratedThemeDescriptor } from './theme-descriptor-types';

/** The asciidoctor-pdf release these descriptors were derived from. */
export const THEME_DESCRIPTOR_GEM_VERSION = '2.3.24';

/** Every theme key the vendored renderer recognises, with its derived kind and default. */
export const GENERATED_THEME_DESCRIPTORS: readonly GeneratedThemeDescriptor[] = [
  {"key":"abstract.first-line-font-color","category":"abstract","valueKind":"colour"},
  {"key":"abstract.first-line-font-style","category":"abstract","valueKind":"string","defaultValue":"bold"},
  {"key":"abstract.first-line-text-transform","category":"abstract","valueKind":"string"},
  {"key":"abstract.font-color","category":"abstract","valueKind":"colour","defaultValue":"5C6266"},
  {"key":"abstract.font-size","category":"abstract","valueKind":"measurement","defaultValue":"$role_lead_font_size"},
  {"key":"abstract.font-style","category":"abstract","valueKind":"keyword","permittedValues":["normal","bold","italic","bold_italic","normal_italic"],"defaultValue":"italic"},
  {"key":"abstract.line-height","category":"abstract","valueKind":"measurement","defaultValue":"1.4"},
  {"key":"abstract.padding","category":"abstract","valueKind":"measurement","defaultValue":"0"},
  {"key":"abstract.text-align","category":"abstract","valueKind":"keyword","permittedValues":["left","center","right","justify"]},
  {"key":"abstract.title.align","category":"abstract","valueKind":"keyword","permittedValues":["left","center","right","justify"],"defaultValue":"center"},
  {"key":"abstract.title.font-color","category":"abstract","valueKind":"colour","defaultValue":"$heading_font_color"},
  {"key":"abstract.title.font-size","category":"abstract","valueKind":"measurement","defaultValue":"$heading_h4_font_size"},
  {"key":"abstract.title.font-style","category":"abstract","valueKind":"keyword","permittedValues":["normal","bold","italic","bold_italic","normal_italic"],"defaultValue":"$heading_font_style"},
  {"key":"abstract.title.text-align","category":"abstract","valueKind":"keyword","permittedValues":["left","center","right","justify"],"defaultValue":"center"},
  {"key":"admonition.column-rule-color","category":"admonition","valueKind":"colour","defaultValue":"$base_border_color"},
  {"key":"admonition.column-rule-style","category":"admonition","valueKind":"string"},
  {"key":"admonition.column-rule-width","category":"admonition","valueKind":"measurement","defaultValue":"$base_border_width"},
  {"key":"admonition.image-width","category":"admonition","valueKind":"measurement"},
  {"key":"admonition.label.font-style","category":"admonition","valueKind":"keyword","permittedValues":["normal","bold","italic","bold_italic","normal_italic"],"defaultValue":"bold"},
  {"key":"admonition.label.min-width","category":"admonition","valueKind":"measurement"},
  {"key":"admonition.label.padding","category":"admonition","valueKind":"measurement"},
  {"key":"admonition.label.text-align","category":"admonition","valueKind":"keyword","permittedValues":["left","center","right","justify"]},
  {"key":"admonition.label.text-transform","category":"admonition","valueKind":"keyword","permittedValues":["none","uppercase","lowercase","capitalize"],"defaultValue":"uppercase"},
  {"key":"admonition.label.vertical-align","category":"admonition","valueKind":"keyword","permittedValues":["top","middle","bottom"]},
  {"key":"admonition.padding","category":"admonition","valueKind":"measurement","defaultValue":"[$vertical_rhythm / 3.0, $horizontal_rhythm, $vertical_rhythm / 3.0, $horizontal_rhythm]"},
  {"key":"base.border-color","category":"base","valueKind":"colour","defaultValue":"EEEEEE"},
  {"key":"base.border-radius","category":"base","valueKind":"measurement","defaultValue":"4"},
  {"key":"base.border-width","category":"base","valueKind":"measurement","defaultValue":"0.5"},
  {"key":"base.font-color","category":"base","valueKind":"colour","defaultValue":"333333"},
  {"key":"base.font-family","category":"base","valueKind":"font","defaultValue":"Noto Serif"},
  {"key":"base.font-kerning","category":"base","valueKind":"string"},
  {"key":"base.font-size","category":"base","valueKind":"measurement","defaultValue":"10.5"},
  {"key":"base.font-size-large","category":"base","valueKind":"measurement","defaultValue":"round($base_font_size * 1.25)"},
  {"key":"base.font-size-min","category":"base","valueKind":"measurement","defaultValue":"$base_font_size * 0.75"},
  {"key":"base.font-size-small","category":"base","valueKind":"measurement","defaultValue":"round($base_font_size * 0.85)"},
  {"key":"base.font-style","category":"base","valueKind":"keyword","permittedValues":["normal","bold","italic","bold_italic","normal_italic"],"defaultValue":"normal"},
  {"key":"base.hyphens","category":"base","valueKind":"string"},
  {"key":"base.line-height","category":"base","valueKind":"measurement","defaultValue":"$base_line_height_length / 10.5"},
  {"key":"base.line-height-length","category":"base","valueKind":"number","defaultValue":"12"},
  {"key":"base.text-align","category":"base","valueKind":"keyword","permittedValues":["left","center","right","justify"],"defaultValue":"justify"},
  {"key":"base.text-decoration-width","category":"base","valueKind":"measurement"},
  {"key":"block.anchor-top","category":"block","valueKind":"string"},
  {"key":"block.margin-bottom","category":"block","valueKind":"measurement","defaultValue":"$vertical_rhythm"},
  {"key":"button.background-color","category":"button","valueKind":"colour"},
  {"key":"button.border-color","category":"button","valueKind":"colour"},
  {"key":"button.border-offset","category":"button","valueKind":"measurement"},
  {"key":"button.border-radius","category":"button","valueKind":"measurement"},
  {"key":"button.border-width","category":"button","valueKind":"measurement"},
  {"key":"button.content","category":"button","valueKind":"string","defaultValue":"[ %s ]"},
  {"key":"button.font-color","category":"button","valueKind":"colour"},
  {"key":"button.font-family","category":"button","valueKind":"font","defaultValue":"Courier"},
  {"key":"button.font-size","category":"button","valueKind":"measurement"},
  {"key":"button.font-style","category":"button","valueKind":"keyword","permittedValues":["normal","bold","italic","bold_italic","normal_italic"],"defaultValue":"bold"},
  {"key":"callout-list.item-spacing","category":"callout-list","valueKind":"measurement"},
  {"key":"callout-list.margin-top-after-code","category":"callout-list","valueKind":"string","defaultValue":"-$block_margin_bottom / 2"},
  {"key":"callout-list.marker-font-color","category":"callout-list","valueKind":"colour"},
  {"key":"caption.align","category":"caption","valueKind":"keyword","permittedValues":["left","center","right","justify","inherit"],"defaultValue":"left"},
  {"key":"caption.background-color","category":"caption","valueKind":"colour"},
  {"key":"caption.font-size","category":"caption","valueKind":"measurement","defaultValue":"$base_font_size * 0.95"},
  {"key":"caption.font-style","category":"caption","valueKind":"keyword","permittedValues":["normal","bold","italic","bold_italic","normal_italic"],"defaultValue":"italic"},
  {"key":"caption.margin-inside","category":"caption","valueKind":"measurement","defaultValue":"$vertical_rhythm / 3"},
  {"key":"caption.margin-outside","category":"caption","valueKind":"number","defaultValue":"0"},
  {"key":"caption.text-align","category":"caption","valueKind":"keyword","permittedValues":["left","center","right","justify","inherit"]},
  {"key":"code.background-color","category":"code","valueKind":"colour","defaultValue":"F5F5F5"},
  {"key":"code.border-color","category":"code","valueKind":"colour","defaultValue":"CCCCCC"},
  {"key":"code.border-radius","category":"code","valueKind":"measurement","defaultValue":"$base_border_radius"},
  {"key":"code.border-width","category":"code","valueKind":"measurement","defaultValue":"0.75"},
  {"key":"code.caption-end","category":"code","valueKind":"string"},
  {"key":"code.font-color","category":"code","valueKind":"colour","defaultValue":"$base_font_color"},
  {"key":"code.font-family","category":"code","valueKind":"font","defaultValue":"$codespan_font_family"},
  {"key":"code.font-size","category":"code","valueKind":"measurement","defaultValue":"ceil($base_font_size)"},
  {"key":"code.highlight-background-color","category":"code","valueKind":"colour"},
  {"key":"code.line-gap","category":"code","valueKind":"measurement","defaultValue":"3.8"},
  {"key":"code.line-height","category":"code","valueKind":"measurement","defaultValue":"1.25"},
  {"key":"code.linenum-font-color","category":"code","valueKind":"colour"},
  {"key":"code.padding","category":"code","valueKind":"measurement","defaultValue":"$code_font_size"},
  {"key":"codespan.background-color","category":"codespan","valueKind":"colour"},
  {"key":"codespan.border-color","category":"codespan","valueKind":"colour"},
  {"key":"codespan.border-offset","category":"codespan","valueKind":"measurement"},
  {"key":"codespan.border-radius","category":"codespan","valueKind":"measurement"},
  {"key":"codespan.border-width","category":"codespan","valueKind":"measurement"},
  {"key":"codespan.font-color","category":"codespan","valueKind":"colour","defaultValue":"B12146"},
  {"key":"codespan.font-family","category":"codespan","valueKind":"font","defaultValue":"M+ 1mn"},
  {"key":"codespan.font-size","category":"codespan","valueKind":"measurement"},
  {"key":"codespan.font-style","category":"codespan","valueKind":"keyword","permittedValues":["normal","bold","italic","bold_italic","normal_italic"]},
  {"key":"conum.font-color","category":"conum","valueKind":"colour","defaultValue":"$codespan_font_color"},
  {"key":"conum.font-family","category":"conum","valueKind":"font","defaultValue":"$codespan_font_family"},
  {"key":"conum.font-size","category":"conum","valueKind":"measurement","defaultValue":"$base_font_size"},
  {"key":"conum.glyphs","category":"conum","valueKind":"string","defaultValue":"circled"},
  {"key":"conum.line-height","category":"conum","valueKind":"measurement","defaultValue":"4 / 3"},
  {"key":"description-list.description-indent","category":"description-list","valueKind":"measurement","defaultValue":"$horizontal_rhythm * 1.25"},
  {"key":"description-list.term-font-style","category":"description-list","valueKind":"string","defaultValue":"bold"},
  {"key":"description-list.term-spacing","category":"description-list","valueKind":"measurement","defaultValue":"$vertical_rhythm / 4"},
  {"key":"example.background-color","category":"example","valueKind":"colour","defaultValue":"$page_background_color"},
  {"key":"example.border-color","category":"example","valueKind":"colour","defaultValue":"$base_border_color"},
  {"key":"example.border-radius","category":"example","valueKind":"measurement","defaultValue":"$base_border_radius"},
  {"key":"example.border-width","category":"example","valueKind":"measurement","defaultValue":"0.75"},
  {"key":"example.caption-end","category":"example","valueKind":"string"},
  {"key":"example.padding","category":"example","valueKind":"measurement","defaultValue":"[$vertical_rhythm, $horizontal_rhythm, $vertical_rhythm, $horizontal_rhythm]"},
  {"key":"font.catalog","category":"font","valueKind":"string"},
  {"key":"font.fallbacks","category":"font","valueKind":"string"},
  {"key":"footer.border-color","category":"footer","valueKind":"colour","defaultValue":"DDDDDD"},
  {"key":"footer.border-width","category":"footer","valueKind":"measurement","defaultValue":"0.25"},
  {"key":"footer.font-size","category":"footer","valueKind":"measurement","defaultValue":"$base_font_size_small"},
  {"key":"footer.height","category":"footer","valueKind":"measurement","defaultValue":"$base_line_height_length * 2.5"},
  {"key":"footer.line-height","category":"footer","valueKind":"measurement","defaultValue":"1"},
  {"key":"footer.padding","category":"footer","valueKind":"measurement","defaultValue":"[$base_line_height_length / 2, 1, 0, 1]"},
  {"key":"footer.recto.right.content","category":"footer","valueKind":"string","defaultValue":"{page-number}"},
  {"key":"footer.verso.left.content","category":"footer","valueKind":"measurement","defaultValue":"$footer_recto_right_content"},
  {"key":"footer.vertical-align","category":"footer","valueKind":"keyword","permittedValues":["top","middle","bottom"],"defaultValue":"top"},
  {"key":"footnotes.font-size","category":"footnotes","valueKind":"measurement","defaultValue":"round($base_font_size * 0.75)"},
  {"key":"footnotes.item-spacing","category":"footnotes","valueKind":"measurement","defaultValue":"$list_item_spacing / 2"},
  {"key":"footnotes.margin-top","category":"footnotes","valueKind":"string"},
  {"key":"header.font-size","category":"header","valueKind":"measurement","defaultValue":"$base_font_size_small"},
  {"key":"header.height","category":"header","valueKind":"measurement"},
  {"key":"header.line-height","category":"header","valueKind":"measurement","defaultValue":"1"},
  {"key":"header.vertical-align","category":"header","valueKind":"keyword","permittedValues":["top","middle","bottom"],"defaultValue":"middle"},
  {"key":"heading.chapter-break-before","category":"heading","valueKind":"string"},
  {"key":"heading.font-color","category":"heading","valueKind":"colour","defaultValue":"$base_font_color"},
  {"key":"heading.font-style","category":"heading","valueKind":"keyword","permittedValues":["normal","bold","italic","bold_italic","normal_italic"],"defaultValue":"bold"},
  {"key":"heading.h1-font-size","category":"heading","valueKind":"measurement","defaultValue":"floor($base_font_size * 2.6)"},
  {"key":"heading.h1-text-align","category":"heading","valueKind":"string"},
  {"key":"heading.h2-font-size","category":"heading","valueKind":"measurement","defaultValue":"floor($base_font_size * 2.15)"},
  {"key":"heading.h2-text-align","category":"heading","valueKind":"string"},
  {"key":"heading.h3-font-size","category":"heading","valueKind":"measurement","defaultValue":"round($base_font_size * 1.7)"},
  {"key":"heading.h4-font-size","category":"heading","valueKind":"measurement","defaultValue":"$base_font_size_large"},
  {"key":"heading.h5-font-size","category":"heading","valueKind":"measurement","defaultValue":"$base_font_size"},
  {"key":"heading.h6-font-size","category":"heading","valueKind":"measurement","defaultValue":"$base_font_size_small"},
  {"key":"heading.line-height","category":"heading","valueKind":"measurement","defaultValue":"1"},
  {"key":"heading.margin-bottom","category":"heading","valueKind":"measurement","defaultValue":"$vertical_rhythm * 0.9"},
  {"key":"heading.margin-page-top","category":"heading","valueKind":"string"},
  {"key":"heading.margin-top","category":"heading","valueKind":"measurement","defaultValue":"$vertical_rhythm * 0.4"},
  {"key":"heading.min-height-after","category":"heading","valueKind":"measurement","defaultValue":"$base_line_height_length * 1.5"},
  {"key":"heading.part-break-after","category":"heading","valueKind":"string"},
  {"key":"heading.part-break-before","category":"heading","valueKind":"string"},
  {"key":"heading.text-align","category":"heading","valueKind":"keyword","permittedValues":["left","center","right","justify"],"defaultValue":"left"},
  {"key":"horizontal-rhythm","category":"horizontal-rhythm","valueKind":"measurement","defaultValue":"$base_line_height_length"},
  {"key":"image.align","category":"image","valueKind":"keyword","permittedValues":["left","center","right","justify"],"defaultValue":"left"},
  {"key":"image.alt-content","category":"image","valueKind":"string"},
  {"key":"image.border-color","category":"image","valueKind":"colour"},
  {"key":"image.border-fit","category":"image","valueKind":"string"},
  {"key":"image.border-width","category":"image","valueKind":"measurement"},
  {"key":"image.caption-end","category":"image","valueKind":"string"},
  {"key":"image.caption-max-width","category":"image","valueKind":"measurement"},
  {"key":"image.float-gap","category":"image","valueKind":"measurement"},
  {"key":"image.width","category":"image","valueKind":"measurement"},
  {"key":"index.column-gap","category":"index","valueKind":"measurement","defaultValue":"$vertical_rhythm"},
  {"key":"index.columns","category":"index","valueKind":"string"},
  {"key":"kbd.background-color","category":"kbd","valueKind":"colour","defaultValue":"F5F5F5"},
  {"key":"kbd.border-color","category":"kbd","valueKind":"colour","defaultValue":"CCCCCC"},
  {"key":"kbd.border-offset","category":"kbd","valueKind":"measurement","defaultValue":"2"},
  {"key":"kbd.border-radius","category":"kbd","valueKind":"measurement","defaultValue":"2"},
  {"key":"kbd.border-width","category":"kbd","valueKind":"measurement","defaultValue":"0.5"},
  {"key":"kbd.font-color","category":"kbd","valueKind":"colour"},
  {"key":"kbd.font-family","category":"kbd","valueKind":"font","defaultValue":"$codespan_font_family"},
  {"key":"kbd.font-size","category":"kbd","valueKind":"measurement"},
  {"key":"kbd.font-style","category":"kbd","valueKind":"keyword","permittedValues":["normal","bold","italic","bold_italic","normal_italic"],"defaultValue":"italic"},
  {"key":"kbd.separator","category":"kbd","valueKind":"string","defaultValue":" + "},
  {"key":"link.background-color","category":"link","valueKind":"colour"},
  {"key":"link.border-offset","category":"link","valueKind":"measurement"},
  {"key":"link.font-color","category":"link","valueKind":"colour","defaultValue":"428BCA"},
  {"key":"link.font-family","category":"link","valueKind":"font"},
  {"key":"link.font-size","category":"link","valueKind":"measurement"},
  {"key":"link.font-style","category":"link","valueKind":"keyword","permittedValues":["normal","bold","italic","bold_italic","normal_italic"]},
  {"key":"link.text-decoration","category":"link","valueKind":"keyword","permittedValues":["none","underline","line-through"]},
  {"key":"link.text-decoration-color","category":"link","valueKind":"colour"},
  {"key":"link.text-decoration-width","category":"link","valueKind":"measurement"},
  {"key":"list.indent","category":"list","valueKind":"measurement","defaultValue":"$horizontal_rhythm * 1.5"},
  {"key":"list.item-spacing","category":"list","valueKind":"measurement","defaultValue":"$vertical_rhythm / 2"},
  {"key":"list.marker-font-color","category":"list","valueKind":"colour"},
  {"key":"list.text-align","category":"list","valueKind":"keyword","permittedValues":["left","center","right","justify"]},
  {"key":"mark.background-color","category":"mark","valueKind":"colour","defaultValue":"FFFF00"},
  {"key":"mark.border-offset","category":"mark","valueKind":"measurement","defaultValue":"1"},
  {"key":"mark.font-color","category":"mark","valueKind":"colour"},
  {"key":"mark.font-style","category":"mark","valueKind":"keyword","permittedValues":["normal","bold","italic","bold_italic","normal_italic"]},
  {"key":"menu.caret-content","category":"menu","valueKind":"string","defaultValue":" <font size=\"1.15em\" color=\"#B12146\">›</font> "},
  {"key":"menu.font-color","category":"menu","valueKind":"colour"},
  {"key":"menu.font-family","category":"menu","valueKind":"font"},
  {"key":"menu.font-size","category":"menu","valueKind":"measurement"},
  {"key":"menu.font-style","category":"menu","valueKind":"keyword","permittedValues":["normal","bold","italic","bold_italic","normal_italic"],"defaultValue":"bold"},
  {"key":"page.background-color","category":"page","valueKind":"colour","defaultValue":"FFFFFF"},
  {"key":"page.column-gap","category":"page","valueKind":"measurement"},
  {"key":"page.columns","category":"page","valueKind":"string"},
  {"key":"page.initial-zoom","category":"page","valueKind":"keyword","permittedValues":["Fit","FitH","FitV"],"defaultValue":"FitH"},
  {"key":"page.layout","category":"page","valueKind":"keyword","permittedValues":["portrait","landscape"],"defaultValue":"portrait"},
  {"key":"page.margin","category":"page","valueKind":"measurement","defaultValue":"[0.5in, 0.67in, 0.67in, 0.67in]"},
  {"key":"page.margin-inner","category":"page","valueKind":"measurement","defaultValue":"0.75in"},
  {"key":"page.margin-outer","category":"page","valueKind":"measurement","defaultValue":"0.59in"},
  {"key":"page.margin-rotated","category":"page","valueKind":"string"},
  {"key":"page.mode","category":"page","valueKind":"keyword","permittedValues":["outline","none","thumbs","fullscreen","fullscreen outline","fullscreen none","fullscreen thumbs"]},
  {"key":"page.numbering.start-at","category":"page","valueKind":"string"},
  {"key":"page.size","category":"page","valueKind":"measurement","defaultValue":"A4"},
  {"key":"prose.margin-bottom","category":"prose","valueKind":"measurement","defaultValue":"$block_margin_bottom"},
  {"key":"prose.margin-inner","category":"prose","valueKind":"measurement"},
  {"key":"prose.text-indent","category":"prose","valueKind":"measurement"},
  {"key":"prose.text-indent-inner","category":"prose","valueKind":"string"},
  {"key":"quote.border-color","category":"quote","valueKind":"colour","defaultValue":"$base_border_color"},
  {"key":"quote.border-left-width","category":"quote","valueKind":"measurement","defaultValue":"$horizontal_rhythm / 3"},
  {"key":"quote.border-width","category":"quote","valueKind":"measurement","defaultValue":"0"},
  {"key":"quote.cite.font-color","category":"quote","valueKind":"colour","defaultValue":"$role_subtitle_font_color"},
  {"key":"quote.cite.font-size","category":"quote","valueKind":"measurement","defaultValue":"$base_font_size_small"},
  {"key":"quote.font-size","category":"quote","valueKind":"measurement","defaultValue":"$base_font_size_large"},
  {"key":"quote.padding","category":"quote","valueKind":"measurement","defaultValue":"[$vertical_rhythm / 4, $horizontal_rhythm, $vertical_rhythm / 4, $horizontal_rhythm + $quote_border_left_width / 2]"},
  {"key":"role.big.font-size","category":"role","valueKind":"measurement","defaultValue":"1.2em"},
  {"key":"role.lead.font-size","category":"role","valueKind":"measurement","defaultValue":"$base_font_size_large"},
  {"key":"role.line-through.text-decoration","category":"role","valueKind":"keyword","permittedValues":["none","underline","line-through"],"defaultValue":"line-through"},
  {"key":"role.small.font-size","category":"role","valueKind":"measurement","defaultValue":"0.8em"},
  {"key":"role.subtitle.font-color","category":"role","valueKind":"colour","defaultValue":"999999"},
  {"key":"role.subtitle.font-size","category":"role","valueKind":"measurement","defaultValue":"0.8em"},
  {"key":"role.subtitle.font-style","category":"role","valueKind":"keyword","permittedValues":["normal","bold","italic","bold_italic","normal_italic"],"defaultValue":"normal_italic"},
  {"key":"role.underline.text-decoration","category":"role","valueKind":"keyword","permittedValues":["none","underline","line-through"],"defaultValue":"underline"},
  {"key":"role.unresolved-font-color","category":"role","valueKind":"colour"},
  {"key":"running-content.start-at","category":"running-content","valueKind":"string"},
  {"key":"section.indent","category":"section","valueKind":"measurement"},
  {"key":"sidebar.background-color","category":"sidebar","valueKind":"colour","defaultValue":"EEEEEE"},
  {"key":"sidebar.border-color","category":"sidebar","valueKind":"colour","defaultValue":"E1E1E1"},
  {"key":"sidebar.border-radius","category":"sidebar","valueKind":"measurement","defaultValue":"$base_border_radius"},
  {"key":"sidebar.border-width","category":"sidebar","valueKind":"measurement","defaultValue":"$base_border_width"},
  {"key":"sidebar.padding","category":"sidebar","valueKind":"measurement","defaultValue":"[$vertical_rhythm, $vertical_rhythm * 1.25, $vertical_rhythm, $vertical_rhythm * 1.25]"},
  {"key":"sidebar.title.align","category":"sidebar","valueKind":"keyword","permittedValues":["left","center","right","justify"],"defaultValue":"center"},
  {"key":"sidebar.title.font-color","category":"sidebar","valueKind":"colour","defaultValue":"$heading_font_color"},
  {"key":"sidebar.title.font-size","category":"sidebar","valueKind":"measurement","defaultValue":"$heading_h4_font_size"},
  {"key":"sidebar.title.font-style","category":"sidebar","valueKind":"keyword","permittedValues":["normal","bold","italic","bold_italic","normal_italic"],"defaultValue":"$heading_font_style"},
  {"key":"sidebar.title.text-align","category":"sidebar","valueKind":"keyword","permittedValues":["left","center","right","justify"],"defaultValue":"center"},
  {"key":"svg.fallback-font-family","category":"svg","valueKind":"font"},
  {"key":"svg.font-family","category":"svg","valueKind":"font"},
  {"key":"table.align","category":"table","valueKind":"keyword","permittedValues":["left","center","right","justify"]},
  {"key":"table.asciidoc-cell-style","category":"table","valueKind":"string"},
  {"key":"table.background-color","category":"table","valueKind":"colour","defaultValue":"$page_background_color"},
  {"key":"table.body.stripe-background-color","category":"table","valueKind":"colour","defaultValue":"F9F9F9"},
  {"key":"table.border-color","category":"table","valueKind":"colour","defaultValue":"DDDDDD"},
  {"key":"table.border-style","category":"table","valueKind":"keyword","permittedValues":["solid","dashed","dotted","double"],"defaultValue":"solid"},
  {"key":"table.border-width","category":"table","valueKind":"measurement","defaultValue":"$base_border_width"},
  {"key":"table.caption-max-width","category":"table","valueKind":"measurement"},
  {"key":"table.cell-line-height","category":"table","valueKind":"measurement"},
  {"key":"table.cell-padding","category":"table","valueKind":"measurement","defaultValue":"3"},
  {"key":"table.foot.background-color","category":"table","valueKind":"colour","defaultValue":"F0F0F0"},
  {"key":"table.foot.font-color","category":"table","valueKind":"colour"},
  {"key":"table.foot.font-family","category":"table","valueKind":"font"},
  {"key":"table.foot.font-size","category":"table","valueKind":"measurement"},
  {"key":"table.foot.font-style","category":"table","valueKind":"keyword","permittedValues":["normal","bold","italic","bold_italic","normal_italic"]},
  {"key":"table.grid-color","category":"table","valueKind":"colour"},
  {"key":"table.grid-style","category":"table","valueKind":"string"},
  {"key":"table.grid-width","category":"table","valueKind":"measurement","defaultValue":"$base_border_width"},
  {"key":"table.head.border-bottom-color","category":"table","valueKind":"colour"},
  {"key":"table.head.border-bottom-style","category":"table","valueKind":"string"},
  {"key":"table.head.border-bottom-width","category":"table","valueKind":"measurement","defaultValue":"$base_border_width * 2.5"},
  {"key":"table.head.cell-padding","category":"table","valueKind":"measurement"},
  {"key":"table.head.font-style","category":"table","valueKind":"keyword","permittedValues":["normal","bold","italic","bold_italic","normal_italic"],"defaultValue":"bold"},
  {"key":"table.head.line-height","category":"table","valueKind":"measurement"},
  {"key":"thematic-break.border-color","category":"thematic-break","valueKind":"colour","defaultValue":"$base_border_color"},
  {"key":"thematic-break.border-style","category":"thematic-break","valueKind":"keyword","permittedValues":["solid","dashed","dotted","double"],"defaultValue":"solid"},
  {"key":"thematic-break.border-width","category":"thematic-break","valueKind":"measurement","defaultValue":"$base_border_width"},
  {"key":"thematic-break.margin-top","category":"thematic-break","valueKind":"string"},
  {"key":"thematic-break.padding","category":"thematic-break","valueKind":"measurement","defaultValue":"[$vertical_rhythm * 0.5, 0]"},
  {"key":"title-page.authors.content","category":"title-page","valueKind":"string"},
  {"key":"title-page.authors.content-name-only","category":"title-page","valueKind":"string"},
  {"key":"title-page.authors.content-with-email","category":"title-page","valueKind":"string"},
  {"key":"title-page.authors.content-with-url","category":"title-page","valueKind":"string"},
  {"key":"title-page.authors.delimiter","category":"title-page","valueKind":"string"},
  {"key":"title-page.authors.display","category":"title-page","valueKind":"string"},
  {"key":"title-page.authors.font-color","category":"title-page","valueKind":"colour","defaultValue":"181818"},
  {"key":"title-page.authors.font-size","category":"title-page","valueKind":"measurement","defaultValue":"$base_font_size_large"},
  {"key":"title-page.authors.margin-bottom","category":"title-page","valueKind":"string"},
  {"key":"title-page.authors.margin-left","category":"title-page","valueKind":"string"},
  {"key":"title-page.authors.margin-right","category":"title-page","valueKind":"string"},
  {"key":"title-page.authors.margin-top","category":"title-page","valueKind":"measurement","defaultValue":"$base_font_size * 1.25"},
  {"key":"title-page.logo.align","category":"title-page","valueKind":"keyword","permittedValues":["left","center","right","justify"]},
  {"key":"title-page.logo.display","category":"title-page","valueKind":"string"},
  {"key":"title-page.logo.image","category":"title-page","valueKind":"string"},
  {"key":"title-page.logo.margin-left","category":"title-page","valueKind":"string"},
  {"key":"title-page.logo.margin-right","category":"title-page","valueKind":"string"},
  {"key":"title-page.logo.top","category":"title-page","valueKind":"measurement","defaultValue":"10%"},
  {"key":"title-page.revision.delimiter","category":"title-page","valueKind":"string"},
  {"key":"title-page.revision.display","category":"title-page","valueKind":"string"},
  {"key":"title-page.revision.margin-bottom","category":"title-page","valueKind":"string"},
  {"key":"title-page.revision.margin-left","category":"title-page","valueKind":"string"},
  {"key":"title-page.revision.margin-right","category":"title-page","valueKind":"string"},
  {"key":"title-page.revision.margin-top","category":"title-page","valueKind":"measurement","defaultValue":"$base_font_size * 1.25"},
  {"key":"title-page.subtitle.display","category":"title-page","valueKind":"string"},
  {"key":"title-page.subtitle.font-size","category":"title-page","valueKind":"measurement","defaultValue":"$heading_h3_font_size"},
  {"key":"title-page.subtitle.font-style","category":"title-page","valueKind":"keyword","permittedValues":["normal","bold","italic","bold_italic","normal_italic"],"defaultValue":"bold_italic"},
  {"key":"title-page.subtitle.line-height","category":"title-page","valueKind":"measurement","defaultValue":"1"},
  {"key":"title-page.subtitle.margin-bottom","category":"title-page","valueKind":"string"},
  {"key":"title-page.subtitle.margin-left","category":"title-page","valueKind":"string"},
  {"key":"title-page.subtitle.margin-right","category":"title-page","valueKind":"string"},
  {"key":"title-page.subtitle.margin-top","category":"title-page","valueKind":"string"},
  {"key":"title-page.text-align","category":"title-page","valueKind":"keyword","permittedValues":["left","center","right","justify"],"defaultValue":"right"},
  {"key":"title-page.title.display","category":"title-page","valueKind":"string"},
  {"key":"title-page.title.font-color","category":"title-page","valueKind":"colour","defaultValue":"$role_subtitle_font_color"},
  {"key":"title-page.title.font-size","category":"title-page","valueKind":"measurement","defaultValue":"$heading_h1_font_size"},
  {"key":"title-page.title.line-height","category":"title-page","valueKind":"measurement","defaultValue":"0.9"},
  {"key":"title-page.title.margin-bottom","category":"title-page","valueKind":"string"},
  {"key":"title-page.title.margin-left","category":"title-page","valueKind":"string"},
  {"key":"title-page.title.margin-right","category":"title-page","valueKind":"string"},
  {"key":"title-page.title.margin-top","category":"title-page","valueKind":"string"},
  {"key":"title-page.title.top","category":"title-page","valueKind":"measurement","defaultValue":"55%"},
  {"key":"toc.break-after","category":"toc","valueKind":"string"},
  {"key":"toc.dot-leader.content","category":"toc","valueKind":"string"},
  {"key":"toc.dot-leader.font-color","category":"toc","valueKind":"colour","defaultValue":"A9A9A9"},
  {"key":"toc.dot-leader.font-size","category":"toc","valueKind":"measurement"},
  {"key":"toc.dot-leader.font-style","category":"toc","valueKind":"keyword","permittedValues":["normal","bold","italic","bold_italic","normal_italic"]},
  {"key":"toc.dot-leader.levels","category":"toc","valueKind":"string"},
  {"key":"toc.hanging-indent","category":"toc","valueKind":"measurement"},
  {"key":"toc.indent","category":"toc","valueKind":"measurement","defaultValue":"$horizontal_rhythm"},
  {"key":"toc.line-height","category":"toc","valueKind":"measurement","defaultValue":"1.4"},
  {"key":"toc.title-text-align","category":"toc","valueKind":"string"},
  {"key":"verse.border-color","category":"verse","valueKind":"colour","defaultValue":"$quote_border_color"},
  {"key":"verse.border-left-width","category":"verse","valueKind":"measurement","defaultValue":"$quote_border_left_width"},
  {"key":"verse.border-width","category":"verse","valueKind":"measurement","defaultValue":"$quote_border_width"},
  {"key":"verse.cite.font-color","category":"verse","valueKind":"colour","defaultValue":"$quote_cite_font_color"},
  {"key":"verse.cite.font-size","category":"verse","valueKind":"measurement","defaultValue":"$quote_cite_font_size"},
  {"key":"verse.font-size","category":"verse","valueKind":"measurement","defaultValue":"$quote_font_size"},
  {"key":"verse.padding","category":"verse","valueKind":"measurement","defaultValue":"$quote_padding"},
  {"key":"vertical-rhythm","category":"vertical-rhythm","valueKind":"measurement","defaultValue":"$base_line_height_length"},
];
