import { randomBytes, createHash } from 'crypto';
import type { Result } from '@asciidocollab/domain';

/**
 * A code the caller must map to its own user-facing wording — {@link exchangeCodeForToken} never
 * returns anything derived from the provider's own response body (which could echo back request
 * parameters, or a provider-authored message not meant for an end user).
 */
export type OAuthExchangeFailureReason =
  /** The token endpoint could not be reached at all (network error, timeout, DNS, TLS, …). */
  | 'network_error'
  /** The token endpoint answered, but not with a `2xx` status. */
  | 'provider_rejected'
  /** The token endpoint answered `2xx`, but the body was not parseable JSON, or carried no usable access token. */
  | 'invalid_response';

/** Refusal returned by {@link exchangeCodeForToken}. Carries no part of the request or response body. */
export interface OAuthExchangeError {
  readonly name: 'OAuthExchangeError';
  readonly reason: OAuthExchangeFailureReason;
}

/** Builds the typed refusal {@link exchangeCodeForToken} returns for a given reason. */
function oauthExchangeError(reason: OAuthExchangeFailureReason): OAuthExchangeError {
  return { name: 'OAuthExchangeError', reason };
}

/** Inputs {@link buildAuthorizeUrl} needs to build one provider's authorization redirect URL. */
export interface BuildAuthorizeUrlInput {
  /** The provider's authorization endpoint (from config — built-in default, or an operator override). */
  authorizeUrl: string;
  /** The OAuth app's client id. */
  clientId: string;
  /** The exact redirect URI registered with the provider. */
  redirectUri: string;
  /** Space-separated scopes requested. */
  scope: string;
  /** The encrypted, opaque (to the provider) state blob minted for this attempt. */
  state: string;
  /** The PKCE `S256` code challenge derived from this attempt's code verifier. */
  codeChallenge: string;
}

/**
 * Builds the URL the browser is redirected to, to start a provider's OAuth authorization-code +
 * PKCE flow. Pure and provider-agnostic: every value the resulting URL needs — including which
 * provider's endpoint to hit — is already resolved by the caller (from config) and passed in, so
 * this function has nothing to look up and nothing that can drift out of sync with the config
 * schema's own per-provider defaults.
 *
 * @param input - The provider's authorize endpoint plus every OAuth parameter to attach.
 * @returns The full authorize URL, including `response_type=code`, `client_id`, `redirect_uri`,
 *   `scope`, `state`, `code_challenge`, and `code_challenge_method=S256`.
 */
export function buildAuthorizeUrl(input: BuildAuthorizeUrlInput): string {
  const url = new URL(input.authorizeUrl);
  url.searchParams.set('response_type', 'code');
  url.searchParams.set('client_id', input.clientId);
  url.searchParams.set('redirect_uri', input.redirectUri);
  url.searchParams.set('scope', input.scope);
  url.searchParams.set('state', input.state);
  url.searchParams.set('code_challenge', input.codeChallenge);
  url.searchParams.set('code_challenge_method', 'S256');
  return url.toString();
}

/**
 * Generates a PKCE code verifier: 32 cryptographically random bytes, base64url-encoded (43
 * characters, no padding) — within RFC 7636's required 43-128 character range and built entirely
 * from its unreserved-character alphabet.
 */
export function generateCodeVerifier(): string {
  return randomBytes(32).toString('base64url');
}

/**
 * Derives a PKCE `S256` code challenge from a code verifier: the base64url-encoded SHA-256 digest
 * of the verifier's ASCII bytes, per RFC 7636.
 *
 * @param codeVerifier - The verifier generated by {@link generateCodeVerifier}.
 * @returns The `S256` code challenge to send at the authorize step.
 */
export function deriveCodeChallenge(codeVerifier: string): string {
  return createHash('sha256').update(codeVerifier, 'ascii').digest('base64url');
}

/** Inputs {@link exchangeCodeForToken} needs to exchange an authorization code for an access token. */
export interface ExchangeCodeForTokenInput {
  /** The provider's token endpoint (from config — built-in default, an operator override, or a test's local mock). */
  tokenUrl: string;
  /** The authorization code the provider's callback redirect carried. */
  code: string;
  /** The PKCE verifier minted for this attempt (matches the challenge sent at the authorize step). */
  codeVerifier: string;
  /** The OAuth app's client id. */
  clientId: string;
  /** The OAuth app's client secret. Sent only in the request body of the server-to-server POST below; never logged. */
  clientSecret: string;
  /** The exact redirect URI used at the authorize step (some providers require it to match again here). */
  redirectUri: string;
}

/** The subset of a token endpoint's JSON response this function actually reads. */
interface TokenResponseBody {
  access_token?: unknown;
  error?: unknown;
}

/** Narrows an unknown JSON value to a plain, non-array object. */
function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * Exchanges an authorization code for an access token at a provider's token endpoint: a
 * server-to-server `POST` (via Node's built-in `fetch`), form-encoded, with `Accept:
 * application/json` sent so every provider — including GitHub, whose default response is
 * form-encoded — answers with a uniformly parseable JSON body.
 *
 * Never logs the code, verifier, client secret, or access token — including on failure: the typed
 * {@link OAuthExchangeError} this returns carries only a coarse {@link OAuthExchangeFailureReason},
 * never any part of the request or the provider's response body (which could otherwise echo
 * request parameters back into a log line or an error surfaced to the caller).
 *
 * @param input - The token endpoint plus every value the exchange needs.
 * @returns The access token on success; a typed, secret-free refusal otherwise.
 */
export async function exchangeCodeForToken(
  input: ExchangeCodeForTokenInput,
): Promise<Result<{ accessToken: string }, OAuthExchangeError>> {
  const body = new URLSearchParams({
    grant_type: 'authorization_code',
    code: input.code,
    redirect_uri: input.redirectUri,
    client_id: input.clientId,
    client_secret: input.clientSecret,
    code_verifier: input.codeVerifier,
  });

  let response: Response;
  try {
    response = await fetch(input.tokenUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        Accept: 'application/json',
      },
      body: body.toString(),
    });
  } catch {
    return { success: false, error: oauthExchangeError('network_error') };
  }

  if (!response.ok) {
    return { success: false, error: oauthExchangeError('provider_rejected') };
  }

  let parsed: unknown;
  try {
    parsed = await response.json();
  } catch {
    return { success: false, error: oauthExchangeError('invalid_response') };
  }

  if (!isPlainObject(parsed)) {
    return { success: false, error: oauthExchangeError('invalid_response') };
  }
  const tokenBody = parsed as TokenResponseBody;
  if (typeof tokenBody.error === 'string' || typeof tokenBody.access_token !== 'string' || tokenBody.access_token.length === 0) {
    return { success: false, error: oauthExchangeError('provider_rejected') };
  }

  return { success: true, value: { accessToken: tokenBody.access_token } };
}
